# Generated by Django 5.0.6 on 2024-05-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportItem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportitem',
            name='submited',
        ),
        migrations.RemoveField(
            model_name='reportitem',
            name='unit',
        ),
    ]
